-- MySQL Script generated by MySQL Workbench
-- Mon Nov 12 18:06:28 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fog` DEFAULT CHARACTER SET utf8 ;
USE `fog` ;

-- -----------------------------------------------------
-- Table `fog`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fog`.`Customer` ;

CREATE TABLE IF NOT EXISTS `fog`.`Customer` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fog`.`Carport`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fog`.`Carport` ;

CREATE TABLE IF NOT EXISTS `fog`.`Carport` (
  `idCarport` INT NOT NULL AUTO_INCREMENT,
  `Height` VARCHAR(45) NULL,
  `Width` VARCHAR(45) NULL,
  `Length` VARCHAR(45) NULL,
  PRIMARY KEY (`idCarport`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fog`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fog`.`Order` ;

CREATE TABLE IF NOT EXISTS `fog`.`Order` (
  `OrderID` INT NOT NULL AUTO_INCREMENT,
  `Polls` INT NOT NULL,
  `Rafter` INT NOT NULL,
  `customerID` INT NOT NULL,
  `idCarport` INT NOT NULL,
  PRIMARY KEY (`OrderID`, `idCarport`),
  INDEX `FK_Customer_idx` (`customerID` ASC),
  INDEX `fk_Order_Carport1_idx` (`idCarport` ASC),
  CONSTRAINT `FK_Customer`
    FOREIGN KEY (`customerID`)
    REFERENCES `fog`.`Customer` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Carport1`
    FOREIGN KEY (`idCarport`)
    REFERENCES `fog`.`Carport` (`idCarport`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fog`.`Materiale`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fog`.`Materiale` ;

CREATE TABLE IF NOT EXISTS `fog`.`Materiale` (
  `Id` INT NOT NULL,
  `Navn` VARCHAR(45) NULL,
  `Pris` INT NULL,
  `Beskrivelse` TEXT NULL,
  `Længde` INT NULL,
  `Enhed` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fog`.`length`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fog`.`length` ;

CREATE TABLE IF NOT EXISTS `fog`.`length` (
  `length` INT NOT NULL,
  PRIMARY KEY (`length`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fog`.`width`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fog`.`width` ;

CREATE TABLE IF NOT EXISTS `fog`.`width` (
  `width` INT NOT NULL,
  PRIMARY KEY (`width`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
